name: Branch Build

on:
  pull_request:
    types: 
      - closed
    branches: 
      - main
      - staging
env:
  TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
